language: php
php:
  - 7.0


install:
  - sudo apt-get update -qq
  - export TEST_PHP_ARGS="--show-diff --show-out"
  - export CC=gcc-4.6 CFLAGS="-g -O0 -fstack-protector -fstack-protector-all"
  - sudo apt-get install -qq $CC
  - $CC --version

script:
  - phpize
  - ./configure --enable-igbinary
  - make
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

branches:
  only:
    - master
