language: php
php:
  - 7.0


install:
  - sudo apt-get update -qq
  - export TEST_PHP_ARGS="--show-diff --show-out"
  - if [ "$VALGRIND" -eq 1 ]; then sudo apt-get install -qq valgrind; export TEST_PHP_ARGS="$TEST_PHP_ARGS -m"; fi
  - sudo apt-get install -qq $CC
  - if [ "$VALGRIND" -eq 1 ]; then valgrind --version; fi
  - $CC --version

script:
  - export CC=gcc-4.6 CFLAGS="-g -O0 -fstack-protector -fstack-protector-all"
  - phpize
  - ./configure --enable-igbinary
  - make
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

branches:
  only:
    - master
